import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// 앱 전체 공통 레이아웃
// - 전체 폰트 설정 
// - 공통 배경색, 기본 텍스트 스타일 
// - 모든 페이지에 공통으로 들어갈 wrapper
// - metadata 기본값

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
